### ISSUE TITLE
Upgrading to 1.3.0 causes Jackson error

### ISSUE THREAD

**Issue by kennyjwilli** [s3-wagon-private/s3-wagon-private#48]
After upgrading to 1.3.0 I receive this error when attempting to deploy artifacts: 

```
                                                     java.lang.Thread.run                    Thread.java:  748
                       java.util.concurrent.ThreadPoolExecutor$Worker.run        ThreadPoolExecutor.java:  624
                        java.util.concurrent.ThreadPoolExecutor.runWorker        ThreadPoolExecutor.java: 1149
                                      java.util.concurrent.FutureTask.run                FutureTask.java:  266
                                                                      ...                                     
                                      clojure.core/binding-conveyor-fn/fn                       core.clj: 1938
                                                        boot.core/boot/fn                       core.clj: 1029
                                                      boot.core/run-tasks                       core.clj: 1019
                                           boot.task.built-in/fn/fn/fn/fn                   built_in.clj:  517
                                           boot.task.built-in/fn/fn/fn/fn                   built_in.clj:  813
                                           boot.task.built-in/fn/fn/fn/fn                   built_in.clj:  994
                                                        boot.pod/call-in*                        pod.clj:  413
                                                                      ...                                     
              org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke    ClojureRuntimeShimImpl.java:  102
              org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke    ClojureRuntimeShimImpl.java:  109
                                                                      ...                                     
                                                        boot.pod/call-in*                        pod.clj:  410
                                                    boot.pod/eval-fn-call                        pod.clj:  359
                                                       clojure.core/apply                       core.clj:  646
                                                                      ...                                     
                                                       boot.aether/deploy                     aether.clj:  354
                                                                      ...                                     
                                       cemerick.pomegranate.aether/deploy                     aether.clj:  407
                                                       clojure.core/apply                       core.clj:  646
                                                                      ...                                     
                             cemerick.pomegranate.aether/deploy-artifacts                     aether.clj:  334
                                                                      ...                                     
         org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy   DefaultRepositorySystem.java:  443
                 org.sonatype.aether.impl.internal.DefaultDeployer.deploy           DefaultDeployer.java:  211
                 org.sonatype.aether.impl.internal.DefaultDeployer.deploy           DefaultDeployer.java:  274
         org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put  WagonRepositoryConnector.java:  467
 org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run  WagonRepositoryConnector.java:  803
   org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon  WagonRepositoryConnector.java:  385
org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon  WagonRepositoryConnector.java:  345
                org.springframework.build.aws.maven.AbstractWagon.connect             AbstractWagon.java:  143
   org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository            PrivateS3Wagon.java:   92
       org.springframework.build.aws.maven.S3Utils.getClientConfiguration                   S3Utils.java:   45
                               com.amazonaws.ClientConfiguration.<clinit>       ClientConfiguration.java:   60
                         com.amazonaws.util.VersionInfoUtils.getUserAgent          VersionInfoUtils.java:   97
                  com.amazonaws.util.VersionInfoUtils.initializeUserAgent          VersionInfoUtils.java:  136
                            com.amazonaws.util.VersionInfoUtils.userAgent          VersionInfoUtils.java:  141
            com.amazonaws.internal.config.InternalConfig$Factory.<clinit>            InternalConfig.java:  304
                        com.amazonaws.internal.config.InternalConfig.load            InternalConfig.java:  249
                    com.amazonaws.internal.config.InternalConfig.loadfrom            InternalConfig.java:  236
                    com.fasterxml.jackson.databind.ObjectMapper.readValue              ObjectMapper.java: 2533
             com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose              ObjectMapper.java: 3564
        com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize          BeanDeserializer.java:  136
 com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize          BeanDeserializer.java:  243
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V
 clojure.lang.ExceptionInfo: com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V
    file: "/tmp/boot.user8387842890285801953.clj"
    line: 23
```

My repo map looks like this: 
```clojure
{:url "s3p://my-bucket/releases/" :no-auth true}
```

And I am using Boot's `push` task.

Additionally, anytime I run `boot show -u` (the Boot command to show any updates to dependencies), I receive the following error: 
```
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.ClientConfiguration
        at org.springframework.build.aws.maven.S3Utils.getClientConfiguration(S3Utils.java:45)
        at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:92)
        at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:143)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:345)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon(WagonRepositoryConnector.java:385)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:571)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by kennyjwilli** [comment]
I believe this could be related to https://github.com/s3-wagon-private/s3-wagon-private/issues/45.

**Comment by Atsman** [comment]
The same problem for me

**Comment by danielcompton** [comment]
1.3.1 is out, has that fixed things for you?
