### ISSUE TITLE
Unnecessary connection refused errors (works in spite of the errors)

### ISSUE THREAD

**Issue by kendagriff** [s3-wagon-private/s3-wagon-private#90]
Could someone help us silence some (apparently) unnecessary errors?

We've deployed our artifacts using [deps-deploy](https://github.com/slipset/deps-deploy), while used s3-wagon-private to consume them in another project.

Strangely, the REPL is throwing connection errors (upon downloading a new version of the artifact), but everything appears to have worked correctly—the artifacts download and are importable in our leiningen project. It's a rather large stack trace, so I won't paste entirely here, but here's the relevant pieces:

```
Sep 21, 2021 10:04:01 AM com.amazonaws.internal.InstanceMetadataServiceResourceFetcher handleException
       WARNING: Fail to retrieve token 
       com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
       	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:62)
       	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:400)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:369)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:365)
       	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:280)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
       	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
       	at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:120)
       	at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:143)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.connectWagon(WagonTransporter.java:343)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.pollWagon(WagonTransporter.java:383)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:432)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:231)
       	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:593)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       	at java.lang.Thread.run(Thread.java:748)
       Caused by: java.net.ConnectException: Connection refused (Connection refused)
       	at java.net.PlainSocketImpl.socketConnect(Native Method)
       	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
       	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
       	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
       	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       	at java.net.Socket.connect(Socket.java:607)
       	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
       	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
       	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
       	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
       	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
```

And more:

```
Sep 21, 2021 10:04:01 AM com.amazonaws.util.EC2MetadataUtils getItems
       WARNING: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
       com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
       	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:62)
       	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:400)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:369)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:365)
       	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:280)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
       	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
       	at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:120)
       	at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:143)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.connectWagon(WagonTransporter.java:343)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.pollWagon(WagonTransporter.java:383)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:432)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:231)
       	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:593)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       	at java.lang.Thread.run(Thread.java:748)
       Caused by: java.net.ConnectException: Connection refused (Connection refused)
       	at java.net.PlainSocketImpl.socketConnect(Native Method)
       	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
       	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
       	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
       	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       	at java.net.Socket.connect(Socket.java:607)
       	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
       	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
       	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
       	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
       	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
```

Yet more...

```
Sep 21, 2021 10:04:01 AM com.amazonaws.http.apache.utils.ApacheUtils noSuchMethodThrownByNormalizeUriInvoker
       WARNING: NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information
       Sep 21, 2021 10:04:04 AM com.amazonaws.internal.InstanceMetadataServiceResourceFetcher handleException
       WARNING: Fail to retrieve token 
       com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
       	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
       	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:62)
       	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:400)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:369)
       	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:365)
       	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:280)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
       	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
       	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
       	at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:120)
       	at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:143)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.connectWagon(WagonTransporter.java:343)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.pollWagon(WagonTransporter.java:383)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:432)
       	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
       	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:231)
       	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:593)
       	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       	at java.lang.Thread.run(Thread.java:748)
       Caused by: java.net.ConnectException: Connection refused (Connection refused)
       	at java.net.PlainSocketImpl.socketConnect(Native Method)
       	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
       	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
       	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
       	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       	at java.net.Socket.connect(Socket.java:607)
       	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
       	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
       	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
       	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
       	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
       	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
       	... 26 more
```

**Comment by kendagriff** [comment]
Appears there's a related issue on this Spring project: https://github.com/spring-cloud/spring-cloud-aws/issues/556
